# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 859909b76c8f4ee35253dbdfd58663071e25abc816697d540152868993f33b91bb8fd6ece692d1f2b3a0a87c08e7e2c15068e3f2d9d73c883430950ca4e2e938

test:
  secret_key_base: a98bdbb4da807e3a90c4790ebfd032399bbb521f45118ed99c6967fda174cc179e7a70930a0ac532e5594c2e9dc37a160980e28964e6257257afd3b7428f8f47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
